### ISSUE TITLE
Unit Tests that test methods with Decompile fail while trying to calculate code coverage

### ISSUE THREAD

**Issue by VenolVl** [hazzik/DelegateDecompiler#15]
Hello, i have encountered an issue with DelegateDecompiler:
When i try to test methods that use Decompile(), those tests are passing when i just run them, but when i try to calculate code coverage i receive following error in every test that use Decompile():

System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Specified cast is not valid.
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Type returnType)
   at DelegateDecompiler.MethodBodyDecompiler.Decompile()
   at DelegateDecompiler.DecompileExtensions.<>c__DisplayClass1.<Decompile>b__0(MethodInfo m)
   at DelegateDecompiler.Cache`2.GetOrAdd(TKey key, Func`2 func)
   at DelegateDecompiler.DecompileExtensions.Decompile(MethodInfo method)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(MethodInfo method, Expression instance, IList`1 arguments)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at DelegateDecompiler.DecompileExtensions.Decompile[T](IQueryable`1 self)
   at IBCM.Models.Readers.TaskReader.<GetPastTasksByCompanyId>d__6.MoveNext() in D:\dev\ibcm\src\Models\Readers\TaskReader.cs:line 41
--- End of stack trace from previous location where exception was thrown ---

I tried using nCrunch, dotCover and Visual Studio Coverage Analyzer, but tests are failing no matter which test engine i am using. As i said it happens only when i try to calculate code coverage, tests are working when i run them manually. Example of method with Decompile:

```
public async virtual Task<Tuple<IEnumerable<TodoInfo>, IEnumerable<MeetingInfo>>> GetPastTasksByContactId(Guid contactId)
        {
            var todoes = await taskService.GetPastTodoesByContactId(contactId).Project().To<TodoInfo>().Decompile().ToListAsync();
            var meetings = await appointmentService.GetPastMeetingsByContactId(contactId).Project().To<MeetingInfo>().Decompile().ToListAsync();

            return new Tuple<IEnumerable<TodoInfo>, IEnumerable<MeetingInfo>>(todoes, meetings);
        }
```

**Comment by mwillebrands** [comment]
Is probably fixed, https://github.com/hazzik/DelegateDecompiler/issues/39

**Comment by BrettBock** [comment]
Still seeing this issue in Visual Studio 2019 Enterprise 16.9.4

**Comment by GravlLift** [comment]
I'm encountering this as well in 0.30.0. `dotnet test` works just fine, as does `dotnet test "--collect:XPlat Code Coverage"`. But `dotnet test "--collect:Code Coverage"` is problematic.

Stepped into it with the debugger. The `instructions` generated below are radically different depending on if `--collect:Code Coverage` is specified or not:
https://github.com/hazzik/DelegateDecompiler/blob/6a2046e8b79e54822bf8cf85f21a4b3b16ec0178/src/DelegateDecompiler/MethodBodyDecompiler.cs#L42-L46

In my case, that results in a stack with a bunch of extraneous `int`s in it, crashing when it tries to call `HasValue` on an `Int32` when it's supposed to be calling it on a nullable `DateTimeOffset`.

Good instructions:
![image](https://user-images.githubusercontent.com/27774026/163434454-1ed60b08-9626-444e-88d7-3665831bc192.png)
Bad instructions:
![image](https://user-images.githubusercontent.com/27774026/163434390-4566cd76-279a-492a-b197-0eab89da6b74.png)

Bad stack, after popping off an `Int32` to throw an ArgumentException:
![image](https://user-images.githubusercontent.com/27774026/163434942-ca924af5-f0db-40b6-add5-53d96b7e28af.png)

Good stack, empty after correctly popping the nullable `DateTimeOffset`:
![image](https://user-images.githubusercontent.com/27774026/163435030-db7d2152-ae00-46f6-8db5-dbfc57473ceb.png)

**Comment by GravlLift** [comment]
Totally unrelated to DelegateDecompiler, but for anyone else who stumbles onto this thread my particular issues were solved by replacing any calls to `DateTime.Now` with a clock interface and controlling time in my tests.

**Comment by GravlLift** [comment]
@hazzik, I've managed to put together [a minimal reproduction](https://github.com/GravlLift/DelegateDecompilerComponent) for this one. It's very strange.
