### ISSUE TITLE
InvalidCastException when running in Release

### ISSUE THREAD

**Issue by somedave** [hazzik/DelegateDecompiler#40]
I'm having a hard time replicating this one in a simple project or in the test suite, but I'm seeing lots of InvalidCastExceptions when running in a Release build. I have been able to reproduce this behavior in my larger application both locally and on a remote IIS server. I'll continue to try and narrow down the problem, but in the meantime, here's a stack trace:

DelegateDecompiler : System.InvalidCastException
Specified cast is not valid.

   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.ConditionalBranch(Instruction instruction, Func`2 condition)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.ConditionalBranch(Instruction instruction, Func`2 condition)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.ConditionalBranch(Instruction instruction, Func`2 condition)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.ConditionalBranch(Instruction instruction, Func`2 condition)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.ConditionalBranch(Instruction instruction, Func`2 condition)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Instruction last)
   at DelegateDecompiler.Processor.Process(Instruction instruction, Type returnType)
   at DelegateDecompiler.MethodBodyDecompiler.Decompile()
   at DelegateDecompiler.DecompileExtensions.<>c__DisplayClass1.<Decompile>b__0(MethodInfo m)
   at DelegateDecompiler.Cache`2.GetOrAdd(TKey key, Func`2 func)
   at DelegateDecompiler.DecompileExtensions.Decompile(MethodInfo method)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(MethodInfo method, Expression instance, IList`1 arguments)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(MethodInfo method, Expression instance, IList`1 arguments)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(Expression expression)
   at DelegateDecompiler.DecompiledQueryProvider.CreateQuery[TElement](Expression expression)
   at DelegateDecompiler.DecompileExtensions.Decompile[T](IQueryable`1 self)
   at Sipc.BackOffice.Areas.LiquidationManagement.Controllers.LiquidationsController.ClaimsGridRead(Liquidation liquidation, DataSourceRequest request) in e:\Code\Sipc.BackOffice\Sipc.BackOffice\Areas\LiquidationManagement\Controllers\LiquidationsController.cs:line 1133
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.InvokeSynchronousActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)

**Comment by JonPSmith** [comment]
Hi @somedave. I noticed that you are using async. Is the problem not there in sync? The reason I ask is that the DelegateDecopiler [Cache.cs](https://github.com/hazzik/DelegateDecompiler/blob/master/src/DelegateDecompiler/Cache.cs) uses a lock and I don't know how good it is. I would have used a ConcurrectDictionary. Worth looking at.

**Comment by somedave** [comment]
Nah - the actual action is synchronous (notice the call to `InvokeSynchronousActionMethod`). MVC just runs everything through the AsyncControllerActionInvoker first.

I do have some more information though - see the screen shot below for where it's failing.

![image](https://cloud.githubusercontent.com/assets/1020407/5710129/98e7fff0-9a6d-11e4-91f1-fc82da8e684d.png)

**Comment by somedave** [comment]
Also, this looks to be isolated to the exact query I'm running - at least I can't reproduce on other queries. I'm using DeligateDecompiler elsewhere in the project and it works fine in Release mode. 

Another note is that even when I add an explicit check for `LocalVariableInfo` in the `Processor` for `Ldloc_S` and `Ldloc` and I no longer get an exception on my local system when running a Release build, the specific query that was throwing the exception also manages to totally crash the IIS worker for this site. Something is definitely odd, and without understanding what it is (and why it's so bad that the worker process crashes) I don't think a simple fix will cut it.

I'm going to rewrite my query to see if I can get around the problem. I'll let you know if I figure out exactly what statement(s) is causing the issue.

**Comment by hazzik** [comment]
This should be fixed in 0.13.1

**Comment by hazzik** [comment]
I'll fix it as soon as I get to home

**Comment by somedave** [comment]
Awesome, thanks. For what it's worth, I can confirm that the problem exists with the code currently at the head of master. Any idea what the problem is?

**Comment by hazzik** [comment]
Problem that some code has been untested and based on some assumptions, which are wrong. Apparently Mono.Reflection converts indices passed to Ldloc/Stloc to matched LocalVariableInfo. The fix should be similar to e6eec7153aaf31c64490caa6e8d78be6c7aaffab

**Comment by somedave** [comment]
Cool - I'm just going to let you do your thing. I'll be happy to test the fix once it's pushed to the repo. Thanks again.

**Comment by hazzik** [comment]
I've fixed this, please test. I've add some tests when will be at home

**Comment by somedave** [comment]
I can confirm that the change resolves the `InvalidCastException`.

However, now that it's not throwing an exception the query is still causing IIS to kill the worker process. This is probably unrelated to this specific issue and is just showing up now because I get past the exception, so go ahead and leave this issue closed. I'll try and get a dump from IIS to see what's going on and open a new issue once I have more information.

**Comment by hazzik** [comment]
Thanks

**Comment by hazzik** [comment]
This has been released as 0.14.0
