### ISSUE TITLE
ArgumentException - Argument type mismatch when using Double.ToString("0.##") in a decompilable expression

### ISSUE THREAD

**Issue by cervengoc** [hazzik/DelegateDecompiler#62]
In the previous versions I had no problem decompiling this property:

```
public string PackageInfo {
  get { return Quantity.ToString("0.##") + " " + Unit; }
}
```

In the latest version it throws an ArgumentException with the following stack strace.

```
System.ArgumentException: Az argumentumtípusok nem egyeznek
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at DelegateDecompiler.Address.Merge(Expression test, Address address1, Address address2, IDictionary`2 map)
   at DelegateDecompiler.Processor.ProcessorState.Merge(Expression test, ProcessorState leftState, ProcessorState rightState)
   at DelegateDecompiler.Processor.<>c__DisplayClass1c.<ConditionalBranch>b__1b()
   at DelegateDecompiler.Processor.Process()
   at DelegateDecompiler.Processor.Process(VariableInfo[] locals, IList`1 args, Instruction instruction, Type returnType)
   at DelegateDecompiler.MethodBodyDecompiler.Decompile()
   at DelegateDecompiler.DecompileExtensions.<>c__DisplayClass1.<Decompile>b__0(MethodInfo m)
   at DelegateDecompiler.Cache`2.GetOrAdd(TKey key, Func`2 func)
   at DelegateDecompiler.DecompileExtensions.Decompile(MethodInfo method)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(MethodInfo method, Expression instance, IList`1 arguments)
   at DelegateDecompiler.DecompileExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at DelegateDecompiler.DecompileExpressionVisitor.Decompile(Expression expression)
```

Thank you,
Zoltán

**Comment by hazzik** [comment]
Which version does work?

**Comment by cervengoc** [comment]
It seems like the last working version is 0.15.1.

**Comment by hazzik** [comment]
@cervengoc can you please provide the linq expression which is failing?

**Comment by cervengoc** [comment]
@hazzik it was a simple projection. Staying at my original example code, something like

```
queryable.Select(e => new { PackInfo = e.PackageInfo }); 
```

**Comment by hazzik** [comment]
@cervengoc what is the type of Unit? 
Is Quantity or Unit decompilable as well?

**Comment by cervengoc** [comment]
Sorry, for missing that. Quantity is double, Unit is string.

**Comment by hazzik** [comment]
So, the thing is... Somewhere in the code you have an conditional expression, which calls `DelegateDecompiler.Address.Merge` but I do not see it in the example above

**Comment by hazzik** [comment]
I believe this is the same as #58

**Comment by cervengoc** [comment]
Hm... interesting. I can remember that when I removed the ToString call, it worked fine. If this is caused by some conditional expression, shouldn't it have crashed in that case too?

**Comment by hazzik** [comment]
@cervengoc yes, I'm sure

**Comment by cervengoc** [comment]
Ok, thank you. So I'm gonna wait for that fix and try when it's out.
Have a nice day.
